### ISSUE TITLE
Guide & Travel Agent (Admin) Accounts | Payments Module | Payment History Section

### ISSUE THREAD

**Issue by sebas-led** [toursbylocals/wiki#176] opened 2024-01-19 20:50 UTC
## SUMMARY
Both, Guides and Agents (Admins only) have the ability to see their balance, withdraw the funds and see all the payout history.

This ticket is to create the Payment History Section with the following sections:
- List View with:
   - Payment Date
   - Amount paid in payout currency
   - Payment method
   - Reference ID
   - Actions > If clicked, opens the Payment Details with
      - Payment Date
      - Total amount paid in payout currency
      - Payment Method
      - List view with Transaction Date, Tour Date, Type, Booking References, TBL Invoice ID, Traveler, Amount in payout currency

Note: Payments section for Travel Agents is virtually identical to guide account except for the side nav.

### ACS

- [x] Connect to the front end and replace mocked data
- [x] Create the Payment History Section following the design on `Figma`
- [x] Items on the list view are for each payout sent to the partner (a single row could have multiple bookings)
   - Payment Method can be Direct Deposit, Wire Transfer or PayPal
   - Reference ID comes from the Payout collection
- [x] If user clicks on the actions, opens the details of the transaction
   - Payment Date is the one when the payout took place
   - Transaction Date is the one when the booking was made
   - Tour Date is the one when the tour took place
   - Type is Sale, Elite Bonus or Adjustment

### VISUALS
**Desktop initial state**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9MQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3f3abbb54ed26b53e97ac3c54e4ef65ed4e1739/Screenshot%202023-11-13%20at%2013.32.23.png)

**Desktop for Payment Details**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODNMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44195f7f1245aefa94bcecdf2f26a96377c98606/Screenshot%202023-11-13%20at%2013.31.50.png)

**Tablet**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUxMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f194a93c375883eccdc15fdda291886b6ae48759/Screenshot%202023-11-13%20at%2013.32.53.png)

**Mobile**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVBMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2719598be77cc429c1d55ef5faf255162f9d5d4/Screenshot%202023-11-13%20at%2013.33.10.png)

### RESOURCES
[Figma Link to Payments](https://www.figma.com/file/05Lni9rdCbn4jzXrvnaYPe/Kitchen?type=design&node-id=1730-124384&mode=design&t=8Dn4GXRZpQG49pXj-0)

[Figma Link to Prototype](https://www.figma.com/proto/05Lni9rdCbn4jzXrvnaYPe/Kitchen?page-id=1730%3A124384&type=design&node-id=2042-51685&t=8Dn4GXRZpQG49pXj-0&scaling=scale-down&starting-point-node-id=2042%3A51685&show-proto-sidebar=1)

**Comment by YumiKimbara** [comment] 2024-02-23 22:05
@kateinvan @sebas-led @laskokonopa @ecurtosi99 @Mica-pfl
Can you check the URL below when you have time?

https://kitchen-staging.toursbylocals.com/guide/payments
https://kitchen-staging.toursbylocals.com/agent/payments

[ykimbara@toursbylocals.com](mailto:ykimbara@toursbylocals.com)
Cupcake1234!

**Comment by kateinvan** [comment] 2024-02-23 23:10
@sebas-led I think we should change the label 'Type' to 'Entry type' as I just changed it on the Accounting module. 
<img width="995" alt="Screenshot 2024-02-23 at 2 59 53 PM" src="https://github.com/toursbylocals/wiki/assets/113576283/af478a98-52b1-4e53-9fc3-1336108aca5a">

**Comment by laskokonopa** [comment] 2024-02-24 00:09
lgtm

**Comment by sebas-led** [comment] 2024-02-24 00:20
@YumiKimbara Looking amazing Yumi, great work ! Few comments:
- I think you are fetching the Reference from accountentries.guide.paidOutBy when accountentries.entryType is "Guide Payment" but it should be accountentries.authorizationId when accountentries.entryType is "Guide Payment". @nk18chi or @DongJoSuh Could you confirm?
- When opening details of the Payment, Traveller should display Traveller Full Name and not TravellerId. Could you change this please?
- Agree with Kate, if possible to change the heading to Entry Type

**Comment by DongJoSuh** [comment] 2024-02-26 17:47
@sebas-led @YumiKimbara do we know what is reference represents? i would ask the accounting/designer what they want to see. i assume it will be either paymentBatchid or authorizationId?

**Comment by YumiKimbara** [comment] 2024-02-26 18:04
@sebas-led @DongJoSuh I am using paymentBatchid for now since we talked about that with Joe and Naoki in the Slack channel.

**Comment by YumiKimbara** [comment] 2024-02-27 04:14
memo to myself: for a reference number, use authorizationId and paymentBatchId in case there is no authorizationId. (confirmed with Joe)

**Comment by YumiKimbara** [comment] 2024-02-28 00:01
@kateinvan @sebas-led @laskokonopa @ecurtosi99 @Mica-pfl
I fixed based on QA Can you check the URL below when you have time?

https://kitchen-staging.toursbylocals.com/guide/payments
https://kitchen-staging.toursbylocals.com/agent/payments

[ykimbara@toursbylocals.com](mailto:ykimbara@toursbylocals.com)
Cupcake1234!

**Comment by kateinvan** [comment] 2024-02-28 16:59
- for the travel agent account, I got an error when I clicked the first payment history 'Jun 29, 2013'
<img width="710" alt="Screenshot 2024-02-28 at 8 59 15 AM" src="https://github.com/toursbylocals/wiki/assets/113576283/db41d4a6-08a6-4a2a-a26a-c4fd0d478a61">

other than that, LGTM

**Comment by YumiKimbara** [comment] 2024-02-28 17:02
@kateinvan Sorry, I am still working on this task (I deleted the comment to ask QA). I will let you know once I am ready for QA again!

**Comment by YumiKimbara** [comment] 2024-02-28 18:10
@kateinvan @sebas-led @laskokonopa @ecurtosi99 @Mica-pfl
I finished the fixing. Can you check the URL below when you have time?

https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/guide/payments
https://tblv3-kitchen-staging-c94ff87374cd.herokuapp.com/agent/payments

[ykimbara@toursbylocals.com](mailto:ykimbara@toursbylocals.com)
Cupcake1234!

**Comment by sebas-led** [comment] 2024-02-28 20:35
@YumiKimbara 
- I think you updated `Reference` in the list view but not when you click on View icon
<img width="1056" alt="Screenshot 2024-02-28 at 14 34 39" src="https://github.com/toursbylocals/wiki/assets/107880609/547cbcbe-09e5-43e7-aae6-5aebfdc9941f">
<img width="1051" alt="Screenshot 2024-02-28 at 14 34 51" src="https://github.com/toursbylocals/wiki/assets/107880609/430f61f8-dce0-4c7f-b4e6-f100f3314712">
Could you take a look? Other than that, LGTM

**Comment by kateinvan** [comment] 2024-02-28 21:39
@YumiKimbara for the travel agent account, the data on the Amount Owing didn't show.
other than that, LGTM
<img width="1077" alt="Screenshot 2024-02-28 at 1 38 26 PM" src="https://github.com/toursbylocals/wiki/assets/113576283/a21b12db-07b1-4578-8b02-021c86e5f87b">

**Comment by YumiKimbara** [comment] 2024-02-28 23:17
@kateinvan on the second row, this data doesn't hold both traveler name and amount owing on the database, so it is empty. If we use real data, I don't think this issue will happen.

**Comment by YumiKimbara** [comment] 2024-02-29 00:11
@kateinvan @sebas-led @laskokonopa @ecurtosi99 @Mica-pfl
The issue Seba pointed out has been fixed now. Can you check the URL below when you have time?

https://kitchen-staging.toursbylocals.com/guide/payments
https://kitchen-staging.toursbylocals.com/agent/payments

[ykimbara@toursbylocals.com](mailto:ykimbara@toursbylocals.com)
Cupcake1234!

**Comment by kateinvan** [comment] 2024-02-29 00:19
LGTM!

**Comment by Mica-pfl** [comment] 2024-02-29 14:22
The agents history is showing me different things when I go to see details for the payments on payments history. 

Payment 1
<img width="1120" alt="Screenshot 2024-02-29 at 11 20 03 AM" src="https://github.com/toursbylocals/wiki/assets/107880911/2192ebf7-d4ca-45a2-ba8a-94e40f312e4f">

Payment 2 
<img width="1079" alt="Screenshot 2024-02-29 at 11 20 28 AM" src="https://github.com/toursbylocals/wiki/assets/107880911/69d35415-30fd-414f-a025-bedc824d1de5">

**Comment by sebas-led** [comment] 2024-02-29 17:21
LGTM 
@YumiKimbara However, I would like to be able to test with any guide/agent. However, I get an error state when going on any other account as Balance is not showing and that doesn't allow me to see the Balance History. Is there anything we could do to finalize that part?

**Comment by kateinvan** [comment] 2024-02-29 18:14
@YumiKimbara hey Yumi, I'm currently working on TA test and I found an issue.
I'm using this credential, which shows an error and I can't return to another tab.
- Username: sleder@toursbylocals.com
<img width="1218" alt="Screenshot 2024-02-29 at 10 12 11 AM" src="https://github.com/toursbylocals/wiki/assets/113576283/a6ec751e-c4a7-4f48-8055-beed33260573">
could you check?

**Comment by YumiKimbara** [comment] 2024-02-29 19:41
@Mica-pfl @sebas-led 
I think after Balance section task needs to be done to see the real data. I am just adding random payment history for now, but logic should be fine :)

**Comment by YumiKimbara** [comment] 2024-02-29 19:43
@kateinvan Yeah, whenever user doesn't have any payment history information (the image you showed me) or whenever there is an issue (error feedback),  you will see the image like that.
Should I show the tab in both cases too?

**Comment by kateinvan** [comment] 2024-02-29 19:49
@YumiKimbara thanks for checking it, and Yes. we need to show the tab menu in both cases :) the error should be placed under the tab area.

**Comment by YumiKimbara** [comment] 2024-03-01 22:07
@kateinvan @sebas-led 

The tab issue has been now fixed. If you access to agent page, you can see now that the empty feedback is under tab (same when error feedback)

https://kitchen-staging.toursbylocals.com/agent/payments

[ykimbara@toursbylocals.com](mailto:ykimbara@toursbylocals.com)
Cupcake1234!

**Comment by sebas-led** [comment] 2024-03-01 22:31
LGTM

**Closed** 2024-03-01 22:35 UTC
Labels: backend

**Comment by kateinvan** [comment] 2024-03-01 22:43
LGTM thanks!
